# ── colors ───────────────────────────────────────────
background            #070707
foreground            #e0e0e0
cursor                #f8f8f2
cursor_text_color     #0d0d0d

# ── cursor ───────────────────────────────────────────
cursor_blink_interval 0

# ── env ──────────────────────────────────────────────
term                  xterm-256color

# ── font ─────────────────────────────────────────────
font_size             13
font_family family="Red Hat Mono" style="Light"
# font_family           family="Chivo Mono" style="Light"
bold_font             no # family="Red Hat Mono" style="Light"
italic_font           no
bold_italic_font      no

adjust_line_height    2
# adjust_column_width 1

# family="Geist Mono"                    # Regular, 13, adjust_line_height 2
# family="Martian Mono" style="Light"    # 12, adjust_line_height 2
# family="Andale Mono"                   # Regular, 13, adjust_line_height 2
# family="MesloLGMDZ Nerd Font Propo"
# family="DejaVuSansM Nerd Font"
# family="Commit Mono Nerd Font"         # adjust_line_height 4
# family="Monaspace Argon" style="ExtraLight"
# family="Departure Mono Nerd Font"
# family="Monaspace Xenon" style="Light"

# ── scrolling ────────────────────────────────────────
scrollback_lines      2000

# ── window ───────────────────────────────────────────
macos_titlebar_color  dark
window_padding_width  10 10

remember_window_size  no
initial_window_width  200c
initial_window_height 65c

