# ── colors ───────────────────────────────────────────
background            #070707
foreground            #e0e0e0
cursor                #f8f8f2
cursor_text_color     #0d0d0d

# ── cursor ───────────────────────────────────────────
cursor_blink_interval 0

# ── env ──────────────────────────────────────────────
term                  xterm-256color

# ── font ─────────────────────────────────────────────
# kitty +list-fonts | grep -i incons
font_size             13

font_family           family="JetBrainsMonoNL Nerd Font Mono" style="Thin"
bold_font             family="JetBrainsMonoNL Nerd Font Mono" style="Thin"
italic_font           family="JetBrainsMonoNL Nerd Font Mono" style="Thin"
bold_italic_font      family="JetBrainsMonoNL Nerd Font Mono" style="Thin"

adjust_line_height    2
# adjust_column_width 1

# family="Red Hat Mono" style="Light"
# family="Geist Mono"                    # Regular, 13, adjust_line_height 2
# family="Martian Mono" style="Light"    # 12, adjust_line_height 2
# family="Andale Mono"                   # Regular, 13, adjust_line_height 2
# family="MesloLGMDZ Nerd Font Propo"
# family="DejaVuSansM Nerd Font"
# family="Commit Mono Nerd Font"         # adjust_line_height 4
# family="Departure Mono Nerd Font"         # <- 
# family="Monaspace Xenon" style="Light"

# ── scrolling ────────────────────────────────────────
scrollback_lines      2000

# ── window ───────────────────────────────────────────
macos_titlebar_color  dark
window_padding_width  10 10

# ── window: aerospace custom ───────────────────────────────────────────
# Config window for aerospace usage along with kitty
# remember_window_size   no
# initial_window_width   185c
# initial_window_height  55c

# ── tabs ───────────────────────────────────────────
tab_bar_edge                top
tab_bar_margin_width        5
tab_bar_margin_height       10 0
tab_bar_style               fade
tab_fade                    0
tab_title_template          "{fmt.bg._080808}{fmt.fg._303030}{fmt.fg.default}{fmt.bg._303030}{fmt.fg._c6c6c6} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._303030}{fmt.fg.default}"
active_tab_title_template   "{fmt.bg._080808}{fmt.fg._80a0ff}{fmt.fg.default}{fmt.bg._80a0ff}{fmt.fg._080808} {title} {fmt.fg.default}{fmt.bg.default}{fmt.fg._80a0ff}{fmt.fg.default}"

# ── tabs: shortcut ─────────────────────────────────────
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# ── tabs: rename ─────────────────────────────────────
map cmd+shift+e   set_tab_title

